// <auto-generated />
using System;
using API.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace API.Migrations
{
    [DbContext(typeof(DoorManagementDbContext))]
    [Migration("20210318114511_InsertData")]
    partial class InsertData
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.4")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("API.Models.Door", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsLocked")
                        .HasColumnType("bit");

                    b.Property<bool>("IsOpen")
                        .HasColumnType("bit");

                    b.Property<string>("Label")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Doors");

                    b.HasData(
                        new
                        {
                            Id = new Guid("ea4a8758-a8c3-408d-8167-f0983ec13916"),
                            IsLocked = false,
                            IsOpen = false,
                            Label = "Maintenance facilities"
                        },
                        new
                        {
                            Id = new Guid("1bf57c7c-2c56-4428-817c-68389371ae91"),
                            IsLocked = true,
                            IsOpen = false,
                            Label = "Warehouse Door"
                        },
                        new
                        {
                            Id = new Guid("9ef73387-bc4f-4783-857e-fae378082161"),
                            IsLocked = false,
                            IsOpen = true,
                            Label = "Corridors"
                        },
                        new
                        {
                            Id = new Guid("d0d68548-2542-4569-a23e-8b7e0bcb780c"),
                            IsLocked = false,
                            IsOpen = true,
                            Label = "Terrace Door"
                        },
                        new
                        {
                            Id = new Guid("f7733007-aca8-4ad5-9fec-bd273ce284ab"),
                            IsLocked = false,
                            IsOpen = true,
                            Label = "Washing Area"
                        },
                        new
                        {
                            Id = new Guid("4ac81f1c-9a70-45fb-92a2-2ffcfdd02de3"),
                            IsLocked = false,
                            IsOpen = true,
                            Label = "Emergency Door"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
