// <auto-generated />
using System;
using API.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace API.Migrations
{
    [DbContext(typeof(DoorManagementDbContext))]
    partial class DoorManagementDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.4")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("API.Models.Door", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsLocked")
                        .HasColumnType("bit");

                    b.Property<bool>("IsOpen")
                        .HasColumnType("bit");

                    b.Property<string>("Label")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Doors");

                    b.HasData(
                        new
                        {
                            Id = new Guid("2a2be9c1-6545-488a-95f4-bead5de83b8f"),
                            IsLocked = false,
                            IsOpen = false,
                            Label = "Maintenance facilities"
                        },
                        new
                        {
                            Id = new Guid("bb73aa08-221f-4f48-8bc7-fcadaf79eb83"),
                            IsLocked = true,
                            IsOpen = false,
                            Label = "Warehouse Door"
                        },
                        new
                        {
                            Id = new Guid("a1e78914-f5ef-41c6-982a-d1bbedff8f4c"),
                            IsLocked = false,
                            IsOpen = true,
                            Label = "Corridors"
                        },
                        new
                        {
                            Id = new Guid("d67a2438-3a5f-47db-a375-f60ccb766645"),
                            IsLocked = false,
                            IsOpen = true,
                            Label = "Terrace Door"
                        },
                        new
                        {
                            Id = new Guid("d7b1354d-eb8e-44d6-ae3e-8fe983bd8ddd"),
                            IsLocked = false,
                            IsOpen = true,
                            Label = "Washing Area"
                        },
                        new
                        {
                            Id = new Guid("c028e9df-7623-4866-8087-1ff810208e34"),
                            IsLocked = false,
                            IsOpen = true,
                            Label = "Emergency Door"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
